#!/usr/bin/python

from pyinp import lines, args
import argparse

if len(args) == 0:
    for line in lines:
        print(line)
else:
    search_for = args[0]

    for line in lines:
        if search_for in line:
            pos = line.index(search_for)
            print(line[0:pos+1])
            break
        else:
            print(line)
